# Generated by Django 3.0 on 2021-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INET2021', '0002_auto_20210823_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
