# Generated by Django 3.0 on 2021-08-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INET2021', '0003_auto_20210819_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='percentage',
            field=models.BooleanField(default=0),
        ),
    ]
