# Generated by Django 3.0 on 2021-08-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INET2021', '0004_local_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
