# Generated by Django 3.0 on 2021-08-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INET2021', '0005_auto_20210820_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='percentage',
            field=models.FloatField(default=None),
        ),
    ]
