# Generated by Django 3.0 on 2021-08-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INET2021', '0006_auto_20210820_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='percentage',
        ),
    ]
