# Generated by Django 3.0 on 2021-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INET2021', '0007_remove_local_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='nomvre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='nomvre',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='manager',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
